# Generated by Django 5.1.2 on 2024-10-18 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LITRevu', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
