# Generated by Django 5.1.2 on 2024-11-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LITRevu', '0005_ticket_author_ticket_book_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='review_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
