# Generated by Django 5.1.2 on 2024-12-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LITRevu', '0010_remove_critique_comment_remove_critique_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='critique',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
