# Generated by Django 5.1.2 on 2024-12-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LITRevu', '0012_ticket_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
