# Generated by Django 5.1.2 on 2024-12-13 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LITRevu', '0016_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
